### ISSUE TITLE
Snippet option to prevent jQuery loading (twice) ?

### ISSUE THREAD

**Issue by hitodev** [HitkoDev/Videobox-MODX#2]
hello

First thank you very much for your extra.

For information, when jQuery is already loaded before videobox snippet call, I need to comment the following line in videobox.class.php :

`//w.mod DISABLED $this->modx->regClientScript($this->config['assets_url'] . 'js/jquery.min.js');`

Without that videobox snippet breaks some JS and I get errors. 

A snippet option to prevent jQuery loading will be appreciated !

Something like &loadjquery=`0`

**Comment by HitkoDev** [comment]
This could easily be achieved by changing that line to

``` php
if(!isset($this->config['loadjquery']) || $this->config['loadjquery']) $this->modx->regClientScript($this->config['assets_url'] . 'js/jquery.min.js');
```

However, Videobox 6 no longer needs jQuery, so you can update to the latest RC to fix your problem.
