### ISSUE TITLE
Videobox title Youtube

### ISSUE THREAD

**Issue by griale46** [HitkoDev/Videobox-MODX#5]
Good afternoon. I use Videobox on modx. Tell me how to output the title of the YouTube video?
Now I bring out here so
[[Videobox?
& display = `box` & videos =` https://www.youtube.com/watch?v=XfSfK8AkGVo`]]
But the video title is not displayed

**Comment by emilas44** [comment]
Hi griale46, sorry but I don't work for the company where I have used Modx so I don't have access to that code anymore... and I really forgot how did I do that...

**Comment by HitkoDev** [comment]
You should use

```
[[Videobox? &display=`box` &videos=`https://www.youtube.com/watch?v=XfSfK8AkGVo|Your title`]]
```
